### ISSUE TITLE
Bigger textboxes

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/elescout#7]
have a large textbox element that is just 4x the vertical detention of the current textboxes to allow for multi-line viewing of text

**Comment by sjcbulldog** [comment]
To be sure, what are you looking for ...
o  Longer text field that can accomodate more characters without scrolling?
o  Larger text font so that the text field is taller and wider so its easier to read, but no more characters are vislble?

**Comment by AarushPalve** [comment]
I was intending for a larger text field that can accommodate more characters (extended vertically).
-Aarush

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sjcbulldog** [comment]
Ok, your comment confused me more.  Extending it vertically means you want a multi-line text box.  Is this what you are looking for?

**Comment by sjcbulldog** [comment]
Ok, here is what I did ...

If you just specify the maxlen property, this will limit the number of characters you can enter and has no impact on the visual appearance of the field.

If you add a 'cols' property, then the visual width of the field will be approximately 'cols' columns wide.  It is approximate because variable width fonts are used and the width will be 'cols' width of the widest character in the font.  This usually means that the width will seem to be wider than what you asked for.

If you add a 'rows' property, then the field will be a multiline field.  Note, in this case both the 'rows' and the 'cols' properties must be provided.

This will be in the next version.

**Comment by sjcbulldog** [comment]
Updated per my last command, there is now an optional rows and cols property.
